Repository matrix-org/matrix-rich-text-editor, pull requests merged in 2022-08, with the labels that each got.

#11 [Android] Add library target to Makefile
  Makefile
Labels: Android

#16 Add capability to set multiple bold formatting nodes
  crates/wysiwyg/src/composer_model.rs
  crates/wysiwyg/src/dom.rs
Labels: Rust

#21 Split dom in different modules.
  crates/wysiwyg/src/composer_model.rs
  crates/wysiwyg/src/dom/dom_handle.rs
  crates/wysiwyg/src/dom/element.rs
  crates/wysiwyg/src/dom/find_result.rs
  crates/wysiwyg/src/dom/html_formatter.rs
  crates/wysiwyg/src/dom/mod.rs
  crates/wysiwyg/src/dom/nodes/container_node.rs
  crates/wysiwyg/src/dom/nodes/dom_node.rs
  crates/wysiwyg/src/dom/nodes/formatting_node.rs
  crates/wysiwyg/src/dom/nodes/mod.rs
  crates/wysiwyg/src/dom/nodes/text_node.rs
  crates/wysiwyg/src/dom/range.rs
  crates/wysiwyg/src/dom/to_html.rs
Labels: Rust

#27 Merge Formatting and Hyperlink nodes into ContainerNode.
  crates/wysiwyg/src/composer_model.rs
  crates/wysiwyg/src/dom.rs
  crates/wysiwyg/src/dom/element.rs
  crates/wysiwyg/src/dom/nodes.rs
  crates/wysiwyg/src/dom/nodes/container_node.rs
  crates/wysiwyg/src/dom/nodes/dom_node.rs
  crates/wysiwyg/src/dom/nodes/formatting_node.rs
  crates/wysiwyg/src/dom/nodes/hyperlink_node.rs
Labels: Rust

#28 Remove Element trait, move its contents to ContainerNode.
  crates/wysiwyg/src/dom.rs
  crates/wysiwyg/src/dom/element.rs
  crates/wysiwyg/src/dom/nodes/container_node.rs
Labels: Rust

#29 Add inline code formatting support
  Cargo.lock
  bindings/wysiwyg-ffi/src/ffi_format_type.rs
  bindings/wysiwyg-ffi/src/wysiwyg_composer.udl
  crates/wysiwyg/Cargo.toml
  crates/wysiwyg/src/dom.rs
  crates/wysiwyg/src/dom/html_formatter.rs
  crates/wysiwyg/src/dom/nodes/text_node.rs
  crates/wysiwyg/src/format_type.rs
  platforms/android/library/src/main/java/io/element/android/wysiwyg/ComposerActivity.kt
  platforms/android/library/src/main/java/io/element/android/wysiwyg/EditorEditText.kt
  platforms/android/library/src/main/java/io/element/android/wysiwyg/InputProcessor.kt
  platforms/android/library/src/main/java/io/element/android/wysiwyg/InterceptInputConnection.kt
  platforms/android/library/src/main/java/io/element/android/wysiwyg/RichTextEditor.kt
  platforms/android/library/src/main/java/io/element/android/wysiwyg/extensions/ComposerExtensions.kt
  platforms/android/library/src/main/java/io/element/android/wysiwyg/extensions/RustExtensions.kt
  platforms/android/library/src/main/java/io/element/android/wysiwyg/spans/InlineCodeSpan.kt
  platforms/android/library/src/main/res/drawable/ic_code.xml
  platforms/android/library/src/main/res/layout/view_rich_text_editor.xml
Labels: Android, Rust

#40 Select multiples nodes
  crates/wysiwyg/src/dom/find_range.rs
  crates/wysiwyg/src/dom/find_result.rs
  crates/wysiwyg/src/dom/nodes/container_node.rs
  crates/wysiwyg/src/dom/nodes/dom_node.rs
  crates/wysiwyg/src/dom/range.rs
  crates/wysiwyg/src/tests/testutils_composer_model.rs
Labels: Rust

#52 Implement merging algorithm for structure and formatting nodes
  crates/wysiwyg/src/composer_model.rs
  crates/wysiwyg/src/dom/nodes/container_node.rs
  crates/wysiwyg/src/dom/nodes/dom_node.rs
  crates/wysiwyg/src/node_joiner.rs
  crates/wysiwyg/src/tests/test_characters.rs
  crates/wysiwyg/src/tests/test_deleting.rs
Labels: Rust

#49 Allow formatting of several nodes
  crates/wysiwyg/src/composer_model.rs
  crates/wysiwyg/src/dom/dom_handle.rs
  crates/wysiwyg/src/dom/dom_struct.rs
  crates/wysiwyg/src/dom/find_range.rs
  crates/wysiwyg/src/dom/nodes/container_node.rs
  crates/wysiwyg/src/dom/nodes/dom_node.rs
  crates/wysiwyg/src/dom/parser/parse.rs
  crates/wysiwyg/src/dom/range.rs
  crates/wysiwyg/src/format_nodes.rs
  crates/wysiwyg/src/format_type.rs
  crates/wysiwyg/src/lib.rs
  crates/wysiwyg/src/node_joiner.rs
  crates/wysiwyg/src/tests/testutils_dom.rs
Labels: Rust

#59 Remove redundant node merging strategies
  crates/wysiwyg/src/composer_model.rs
  crates/wysiwyg/src/dom/dom_struct.rs
  crates/wysiwyg/src/dom/nodes/container_node.rs
  crates/wysiwyg/src/dom/range.rs
  crates/wysiwyg/src/format_nodes.rs
  crates/wysiwyg/src/node_joiner.rs
Labels: Rust
